# Generated by Django 5.2.8 on 2025-11-29 15:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('receptionniste', 'Réceptionniste'), ('responsable_materiaux', 'Responsable Matériaux'), ('operateur_route', 'Opérateur Route'), ('operateur_mecanique', 'Opérateur Mécanique'), ('responsable_traitement', 'Responsable Traitement'), ('chef_projet', 'Chef de Projet'), ('chef_service', 'Chef Service Génie Civil'), ('directeur_technique', 'Directeur Technique'), ('directeur_general', 'Directeur Général')], max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('projet', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Echantillon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('nature', models.CharField(choices=[('Sol argileux', 'Sol argileux'), ('Sol sableux', 'Sol sableux'), ('Sol limoneux', 'Sol limoneux'), ('Gravier', 'Gravier'), ('Roche', 'Roche'), ('Latérite', 'Latérite'), ('Tout-venant', 'Tout-venant')], max_length=100)),
                ('profondeur_debut', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('profondeur_fin', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('sondage', models.CharField(choices=[('carotte', 'Carotté'), ('vrac', 'Vrac')], max_length=10)),
                ('nappe', models.CharField(blank=True, help_text='Niveau de la nappe phréatique', max_length=100)),
                ('qr_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='echantillons/')),
                ('date_reception', models.DateField(default=django.utils.timezone.now)),
                ('date_fin_estimee', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('stockage', 'En stockage'), ('essais', 'En essais'), ('decodification', 'Décodification'), ('traitement', 'Traitement'), ('validation', 'Validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='stockage', max_length=20)),
                ('priorite', models.CharField(choices=[('normale', 'Normale'), ('urgente', 'Urgente')], default='normale', max_length=10)),
                ('chef_projet', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echantillons', to='core.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echantillons_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'echantillons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Essai',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('AG', 'Analyse Granulométrique (AG)'), ('Proctor', 'Proctor'), ('CBR', 'CBR'), ('Oedometre', 'Œdomètre'), ('Cisaillement', 'Cisaillement')], max_length=20)),
                ('section', models.CharField(choices=[('route', 'Section Route'), ('mecanique', 'Section Mécanique des Sols')], max_length=15)),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('date_rejet', models.DateField(blank=True, null=True)),
                ('duree_estimee', models.PositiveIntegerField(help_text='Durée en jours')),
                ('operateur', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='attente', max_length=15)),
                ('statut_validation', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('rejected', 'Rejeté')], default='pending', max_length=15)),
                ('resultats', models.JSONField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True)),
                ('commentaires_validation', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='essais/')),
                ('was_resumed', models.BooleanField(default=False, help_text='Essai repris après rejet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('echantillon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essais', to='core.echantillon')),
            ],
            options={
                'db_table': 'essais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('module', models.CharField(blank=True, max_length=100)),
                ('action_required', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('echantillon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.echantillon')),
                ('essai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.essai')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('valide', 'Validé'), ('rejete', 'Rejeté')], max_length=10)),
                ('observations', models.TextField(blank=True)),
                ('niveau', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('echantillon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='core.echantillon')),
                ('validateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'validation_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='echantillon',
            index=models.Index(fields=['statut', 'priorite'], name='echantillon_statut_3cee83_idx'),
        ),
        migrations.AddIndex(
            model_name='echantillon',
            index=models.Index(fields=['date_reception'], name='echantillon_date_re_97f6a2_idx'),
        ),
        migrations.AddIndex(
            model_name='essai',
            index=models.Index(fields=['statut', 'section'], name='essais_statut_7081bf_idx'),
        ),
        migrations.AddIndex(
            model_name='essai',
            index=models.Index(fields=['date_debut'], name='essais_date_de_29b79d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read'], name='notificatio_user_id_1f75db_idx'),
        ),
    ]
