# Generated by Django 5.2.8 on 2025-11-29 17:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantillon',
            name='date_reception',
            field=models.DateField(default=core.models.get_today),
        ),
    ]
