# Generated by Django 5.2.8 on 2025-11-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_echantillon_date_reception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantillon',
            name='qr_code',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
    ]
