# Generated by Django 5.2.8 on 2025-11-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_echantillon_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='date_envoi_essais',
            field=models.DateField(blank=True, help_text="Date d'envoi aux sections pour essais", null=True),
        ),
        migrations.AlterField(
            model_name='echantillon',
            name='nature',
            field=models.CharField(choices=[('Sol', 'Sol'), ('Gravier', 'Gravier')], max_length=100),
        ),
    ]
