# Generated by Django 5.2.8 on 2025-12-10 18:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_echantillon_date_envoi_essais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapaciteLaboratoire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_essai', models.CharField(choices=[('AG', 'Analyse Granulométrique'), ('Proctor', 'Proctor'), ('CBR', 'CBR'), ('Oedometre', 'Œdomètre'), ('Cisaillement', 'Cisaillement')], max_length=20, unique=True)),
                ('capacite_quotidienne', models.PositiveIntegerField()),
                ('capacite_simultanee', models.PositiveIntegerField(blank=True, null=True)),
                ('duree_standard_jours', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'capacites_laboratoire',
            },
        ),
        migrations.AddField(
            model_name='echantillon',
            name='client_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='client_nom',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='date_envoi_ag',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='date_envoi_cbr',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='date_envoi_cisaillement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='date_envoi_oedometre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='date_envoi_proctor',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='date_retour_predite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='essais_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('receptionniste', 'Réceptionniste'), ('responsable_materiaux', 'Responsable Matériaux'), ('operateur_route', 'Opérateur Route'), ('operateur_mecanique', 'Opérateur Mécanique'), ('responsable_traitement', 'Responsable Traitement'), ('chef_projet', 'Chef de Projet'), ('chef_service', 'Chef Service Génie Civil'), ('directeur_technique', 'Directeur Technique'), ('directeur_general', 'Directeur Général'), ('directeur_snertp', 'Directeur SNERTP')], max_length=30),
        ),
        migrations.CreateModel(
            name='PlanificationEssai',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_planifiee', models.DateField()),
                ('date_fin_planifiee', models.DateField()),
                ('capacite_utilisee', models.PositiveIntegerField(default=1)),
                ('contraintes_respectees', models.BooleanField(default=True)),
                ('notes_planification', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('essai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planification', to='core.essai')),
            ],
            options={
                'db_table': 'planifications_essais',
                'ordering': ['date_planifiee'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('signature_directeur', models.TextField(blank=True, help_text='Signature numérique base64')),
                ('observations_chef_service', models.TextField(blank=True)),
                ('observations_directeur_technique', models.TextField(blank=True)),
                ('observations_directeur_snertp', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('chef_service', 'Chez Chef Service'), ('directeur_technique', 'Chez Directeur Technique'), ('directeur_snertp', 'Chez Directeur SNERTP'), ('envoye_client', 'Envoyé au client'), ('rejete', 'Rejeté')], default='en_cours', max_length=20)),
                ('date_envoi_chef_service', models.DateTimeField(blank=True, null=True)),
                ('date_validation_chef_service', models.DateTimeField(blank=True, null=True)),
                ('date_envoi_directeur_technique', models.DateTimeField(blank=True, null=True)),
                ('date_validation_directeur_technique', models.DateTimeField(blank=True, null=True)),
                ('date_envoi_directeur_snertp', models.DateTimeField(blank=True, null=True)),
                ('date_envoi_client', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('echantillon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='core.echantillon')),
            ],
            options={
                'db_table': 'rapports',
                'ordering': ['-created_at'],
            },
        ),
    ]
