# Generated by Django 5.2.8 on 2025-12-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_capacitelaboratoire_echantillon_client_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='date_envoi_chef_projet',
            field=models.DateField(blank=True, help_text="Date d'envoi au chef de projet", null=True),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='date_envoi_traitement',
            field=models.DateField(blank=True, help_text="Date d'envoi au traitement", null=True),
        ),
    ]
