# Generated by Django 5.2.8 on 2025-12-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_echantillon_date_envoi_chef_projet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('receptionniste', 'Réceptionniste'), ('responsable_materiaux', 'Responsable Matériaux'), ('operateur_route', 'Opérateur Route'), ('operateur_mecanique', 'Opérateur Mécanique'), ('responsable_traitement', 'Responsable Traitement'), ('chef_projet', 'Chef de Projet'), ('chef_service', 'Chef Service Génie Civil'), ('directeur_technique', 'Directeur Technique'), ('directeur_general', 'Directeur Général'), ('directeur_snertp', 'Directeur SNERTP'), ('service_marketing', 'Service Marketing')], max_length=30),
        ),
    ]
