# Generated by Django 5.2.8 on 2025-12-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='fichier_traitement',
            field=models.FileField(blank=True, null=True, upload_to='rapports/traitement/'),
        ),
    ]
