# Generated by Django 5.2.8 on 2025-12-16 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rapport_fichier_traitement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacheProgrammee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_tache', models.CharField(choices=[('envoi_essai', 'Envoi Essai'), ('envoi_traitement', 'Envoi Traitement'), ('envoi_validation', 'Envoi Validation')], max_length=20)),
                ('date_execution', models.DateTimeField(help_text="Date et heure d'exécution automatique")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('executee', 'Exécutée'), ('annulee', 'Annulée')], default='en_attente', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('echantillon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches_programmees', to='core.echantillon')),
                ('essai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches_programmees', to='core.essai')),
            ],
            options={
                'db_table': 'taches_programmees',
                'ordering': ['date_execution'],
                'indexes': [models.Index(fields=['statut', 'date_execution'], name='taches_prog_statut_9499c8_idx')],
            },
        ),
    ]
