# Generated by Django 5.2.8 on 2025-12-16 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tacheprogrammee'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportMarketing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_echantillon', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=255)),
                ('file_data', models.TextField(help_text='Fichier PDF en base64')),
                ('signed_report_data', models.TextField(blank=True, help_text='Rapport HTML signé en base64')),
                ('avis_directeur_snertp', models.TextField(blank=True)),
                ('signature_directeur_snertp', models.TextField(blank=True, help_text='Signature en base64')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé au client')], default='en_attente', max_length=20)),
                ('email_client', models.EmailField(blank=True, max_length=254)),
                ('date_envoi_marketing', models.DateTimeField(auto_now_add=True)),
                ('date_envoi_client', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('echantillon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_marketing', to='core.echantillon')),
            ],
            options={
                'db_table': 'rapports_marketing',
                'ordering': ['-created_at'],
            },
        ),
    ]
