# Generated by Django 5.2.8 on 2025-12-16 20:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rapportmarketing'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_echantillon', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=255)),
                ('file_data', models.TextField(help_text='Fichier en base64')),
                ('etape_actuelle', models.CharField(choices=[('chef_projet', 'Chef de Projet'), ('chef_service', 'Chef de Service'), ('directeur_technique', 'Directeur Technique'), ('directeur_snertp', 'Directeur SNERTP'), ('marketing', 'Service Marketing'), ('client', 'Client')], max_length=30)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('date_envoi_chef_projet', models.DateTimeField(blank=True, null=True)),
                ('date_validation_chef_projet', models.DateTimeField(blank=True, null=True)),
                ('comment_chef_projet', models.TextField(blank=True)),
                ('validated_by_chef_projet', models.BooleanField(default=False)),
                ('date_envoi_chef_service', models.DateTimeField(blank=True, null=True)),
                ('date_validation_chef_service', models.DateTimeField(blank=True, null=True)),
                ('comment_chef_service', models.TextField(blank=True)),
                ('validated_by_chef_service', models.BooleanField(default=False)),
                ('date_envoi_directeur_technique', models.DateTimeField(blank=True, null=True)),
                ('date_validation_directeur_technique', models.DateTimeField(blank=True, null=True)),
                ('comment_directeur_technique', models.TextField(blank=True)),
                ('validated_by_directeur_technique', models.BooleanField(default=False)),
                ('date_envoi_directeur_snertp', models.DateTimeField(blank=True, null=True)),
                ('date_validation_directeur_snertp', models.DateTimeField(blank=True, null=True)),
                ('observations_directeur_snertp', models.TextField(blank=True)),
                ('signature_directeur_snertp', models.TextField(blank=True)),
                ('avise_by_directeur_snertp', models.BooleanField(default=False)),
                ('date_envoi_marketing', models.DateTimeField(blank=True, null=True)),
                ('processed_by_marketing', models.BooleanField(default=False)),
                ('date_envoi_client', models.DateTimeField(blank=True, null=True)),
                ('email_client', models.EmailField(blank=True, max_length=254)),
                ('date_rejet', models.DateTimeField(blank=True, null=True)),
                ('raison_rejet', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_created', to=settings.AUTH_USER_MODEL)),
                ('echantillon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_validations', to='core.echantillon')),
            ],
            options={
                'db_table': 'workflow_validations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['etape_actuelle', 'statut'], name='workflow_va_etape_a_529e70_idx'), models.Index(fields=['code_echantillon'], name='workflow_va_code_ec_833ec8_idx')],
            },
        ),
    ]
