# Generated by Django 5.2.8 on 2025-12-17 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_workflowvalidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStorage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_storage',
                'indexes': [models.Index(fields=['user', 'key'], name='data_storag_user_id_1eb0c0_idx')],
                'unique_together': {('user', 'key')},
            },
        ),
    ]
