# Generated by Django 5.2.8 on 2025-12-17 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_workflow_rejection_fields'),
        ('core', '0012_datastorage'),
    ]

    operations = [
    ]
