# Generated by Django 5.2.8 on 2025-12-18 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20251218_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowvalidation',
            name='commentaire_chef_projet',
        ),
        migrations.RemoveField(
            model_name='workflowvalidation',
            name='raison_rejet_chef_projet',
        ),
        migrations.RemoveField(
            model_name='workflowvalidation',
            name='raison_rejet_chef_service',
        ),
        migrations.RemoveField(
            model_name='workflowvalidation',
            name='raison_rejet_directeur_snertp',
        ),
        migrations.RemoveField(
            model_name='workflowvalidation',
            name='raison_rejet_directeur_technique',
        ),
        migrations.RemoveField(
            model_name='workflowvalidation',
            name='rejet_chef_projet',
        ),
        migrations.RemoveField(
            model_name='workflowvalidation',
            name='rejet_chef_service',
        ),
        migrations.RemoveField(
            model_name='workflowvalidation',
            name='rejet_directeur_snertp',
        ),
        migrations.RemoveField(
            model_name='workflowvalidation',
            name='rejet_directeur_technique',
        ),
        migrations.RemoveField(
            model_name='workflowvalidation',
            name='validation_chef_projet',
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, help_text="Nom d'utilisateur au moment de l'action", max_length=150)),
                ('user_role', models.CharField(blank=True, help_text="Rôle de l'utilisateur", max_length=30)),
                ('action_type', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('client_create', 'Création Client'), ('client_update', 'Modification Client'), ('client_delete', 'Suppression Client'), ('client_view', 'Consultation Client'), ('echantillon_create', 'Création Échantillon'), ('echantillon_update', 'Modification Échantillon'), ('echantillon_delete', 'Suppression Échantillon'), ('echantillon_view', 'Consultation Échantillon'), ('echantillon_send_essai', 'Envoi Échantillon aux Essais'), ('echantillon_send_traitement', 'Envoi Échantillon au Traitement'), ('essai_create', 'Création Essai'), ('essai_update', 'Modification Essai'), ('essai_delete', 'Suppression Essai'), ('essai_view', 'Consultation Essai'), ('essai_start', 'Démarrage Essai'), ('essai_complete', 'Finalisation Essai'), ('essai_send', 'Envoi Essai'), ('rapport_create', 'Création Rapport'), ('rapport_update', 'Modification Rapport'), ('rapport_view', 'Consultation Rapport'), ('rapport_validate', 'Validation Rapport'), ('rapport_reject', 'Rejet Rapport'), ('rapport_send', 'Envoi Rapport'), ('workflow_create', 'Création Workflow'), ('workflow_validate', 'Validation Workflow'), ('workflow_reject', 'Rejet Workflow'), ('workflow_advance', 'Avancement Workflow'), ('notification_create', 'Création Notification'), ('notification_read', 'Lecture Notification'), ('api_call', 'Appel API'), ('export', 'Export de données'), ('import', 'Import de données'), ('other', 'Autre action')], max_length=50)),
                ('action_description', models.TextField(blank=True, help_text="Description détaillée de l'action")),
                ('http_method', models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('endpoint', models.CharField(blank=True, help_text="URL de l'endpoint appelé", max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_data', models.JSONField(blank=True, help_text='Données de la requête (POST/PUT/PATCH)', null=True)),
                ('response_status', models.IntegerField(blank=True, help_text='Code de statut HTTP de la réponse', null=True)),
                ('echantillon_id', models.UUIDField(blank=True, null=True)),
                ('echantillon_code', models.CharField(blank=True, max_length=20)),
                ('essai_id', models.UUIDField(blank=True, null=True)),
                ('essai_type', models.CharField(blank=True, max_length=20)),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('client_code', models.CharField(blank=True, max_length=20)),
                ('rapport_id', models.UUIDField(blank=True, null=True)),
                ('workflow_id', models.UUIDField(blank=True, null=True)),
                ('success', models.BooleanField(default=True, help_text="L'action a-t-elle réussi?")),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur si échec")),
                ('duration_ms', models.IntegerField(blank=True, help_text="Durée de l'action en millisecondes", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'action_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='action_logs_user_id_dc8b7c_idx'), models.Index(fields=['action_type', 'created_at'], name='action_logs_action__e860e1_idx'), models.Index(fields=['echantillon_id'], name='action_logs_echanti_46bed2_idx'), models.Index(fields=['essai_id'], name='action_logs_essai_i_65cdbb_idx'), models.Index(fields=['success', 'created_at'], name='action_logs_success_bc6f7d_idx')],
            },
        ),
    ]
