# Generated by Django 5.2.8 on 2025-12-18 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_workflowvalidation_commentaire_chef_projet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssaiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essai_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('echantillon_code', models.CharField(db_index=True, max_length=100)),
                ('essai_type', models.CharField(max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('statut', models.CharField(default='attente', max_length=50)),
                ('validation_status', models.CharField(blank=True, max_length=50)),
                ('envoye', models.BooleanField(default=False)),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('resultats', models.JSONField(blank=True, default=dict)),
                ('commentaires', models.TextField(blank=True)),
                ('operateur', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'essai_data',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['echantillon_code', 'essai_type'], name='essai_data_echanti_393b8a_idx'), models.Index(fields=['statut'], name='essai_data_statut_b238d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='RapportValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_echantillon', models.CharField(db_index=True, max_length=100)),
                ('client_name', models.CharField(max_length=255)),
                ('essai_type', models.CharField(blank=True, max_length=50)),
                ('etape_actuelle', models.CharField(choices=[('chef_projet', 'Chef de Projet'), ('chef_service', 'Chef de Service'), ('directeur_technique', 'Directeur Technique'), ('directeur_snertp', 'Directeur SNERTP'), ('marketing', 'Service Marketing'), ('client', 'Client')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('rejected', 'Rejeté')], db_index=True, default='pending', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_data', models.TextField()),
                ('original_file_name', models.CharField(blank=True, max_length=255)),
                ('original_file_data', models.TextField(blank=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_rejet', models.DateTimeField(blank=True, null=True)),
                ('validated_by_chef_projet', models.BooleanField(default=False)),
                ('rejected_by_chef_projet', models.BooleanField(default=False)),
                ('comment_chef_projet', models.TextField(blank=True)),
                ('date_validation_chef_projet', models.DateTimeField(blank=True, null=True)),
                ('validated_by_chef_service', models.BooleanField(default=False)),
                ('rejected_by_chef_service', models.BooleanField(default=False)),
                ('comment_chef_service', models.TextField(blank=True)),
                ('date_validation_chef_service', models.DateTimeField(blank=True, null=True)),
                ('validated_by_directeur_technique', models.BooleanField(default=False)),
                ('rejected_by_directeur_technique', models.BooleanField(default=False)),
                ('comment_directeur_technique', models.TextField(blank=True)),
                ('date_validation_directeur_technique', models.DateTimeField(blank=True, null=True)),
                ('validated_by_directeur_snertp', models.BooleanField(default=False)),
                ('rejected_by_directeur_snertp', models.BooleanField(default=False)),
                ('avis_directeur_snertp', models.TextField(blank=True)),
                ('signature_directeur_snertp', models.TextField(blank=True)),
                ('date_validation_directeur_snertp', models.DateTimeField(blank=True, null=True)),
                ('processed_by_marketing', models.BooleanField(default=False)),
                ('date_envoi_client', models.DateTimeField(blank=True, null=True)),
                ('email_client', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rapport_validations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code_echantillon', 'etape_actuelle'], name='rapport_val_code_ec_dd0de5_idx'), models.Index(fields=['status', 'etape_actuelle'], name='rapport_val_status_4e34f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanificationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('echantillon_code', models.CharField(db_index=True, max_length=100)),
                ('essai_type', models.CharField(max_length=50)),
                ('date_planifiee', models.DateField()),
                ('operateur_assigne', models.CharField(blank=True, max_length=255)),
                ('priorite', models.CharField(default='normale', max_length=50)),
                ('statut', models.CharField(default='planifie', max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planification_data',
                'ordering': ['date_planifiee'],
                'indexes': [models.Index(fields=['echantillon_code', 'statut'], name='planificati_echanti_e76a94_idx'), models.Index(fields=['date_planifiee'], name='planificati_date_pl_c0adab_idx')],
            },
        ),
    ]
