# Generated by Django 5.2.8 on 2025-12-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_essaidata_rapportvalidation_planificationdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowvalidation',
            name='observations_traitement',
            field=models.TextField(blank=True),
        ),
    ]
