# Generated by Django 5.2.9 on 2025-12-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_final_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowvalidation',
            name='commentaires_rejet',
        ),
        migrations.RemoveField(
            model_name='workflowvalidation',
            name='date_rejet_chef_projet',
        ),
        migrations.RemoveField(
            model_name='workflowvalidation',
            name='date_rejet_chef_service',
        ),
        migrations.AlterField(
            model_name='workflowvalidation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('rejete', 'Rejeté')], default='en_attente', max_length=20),
        ),
    ]
