# Generated by Django 5.2.9 on 2025-12-24 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_workflowvalidation_commentaires_rejet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_echantillon', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=255)),
                ('file_data', models.TextField(help_text='Fichier en base64')),
                ('etape_envoi', models.CharField(choices=[('chef_service', 'Chef Service'), ('directeur_technique', 'Directeur Technique'), ('directeur_snertp', 'Directeur SNERTP'), ('marketing', 'Service Marketing'), ('client', 'Client')], max_length=30)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('commentaires', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envoye_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_archives_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rapports_archives',
                'ordering': ['-date_envoi'],
                'indexes': [models.Index(fields=['code_echantillon'], name='rapports_ar_code_ec_9656ed_idx'), models.Index(fields=['envoye_par', 'etape_envoi'], name='rapports_ar_envoye__e401ca_idx')],
            },
        ),
    ]
