# Generated by Django 5.2.9 on 2025-12-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rapportarchive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tacheprogrammee',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tacheprogrammee',
            name='echantillon',
        ),
        migrations.RemoveField(
            model_name='tacheprogrammee',
            name='essai',
        ),
        migrations.AddField(
            model_name='tacheprogrammee',
            name='created_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tacheprogrammee',
            name='echantillon_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tacheprogrammee',
            name='essai_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
