# Generated by Django 5.0.1 on 2025-12-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_tacheprogrammee_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowvalidation",
            name="client_id",
            field=models.UUIDField(
                blank=True, help_text="ID du client pour regroupement", null=True
            ),
        ),
    ]
